### ISSUE TITLE
[Feature Request] Compile a 100 Qubit QFT

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#262]
Issue Description
-----------------

 As very difficult benchmark circuit we want to compile a 100 qubit QFT.
 
QFTs are a crucial component in many algorithms, such as Phase estimation and Shor's. It pushes the limits of error corrected computations because it requires the ability to perform 

Proposed Solution
-----------------

- [x] Decompose arbitrary gates. Done in #235 and enhanced in #257 to handle smaller angles (to support up to a 150 qubit QFT) 
- [x] Parse Pauli rotations of arbitrarily very small angles. Needed a manual parser because both Qiskit and PyZX run into precision problems when reading `crz` for rotations smaller than `pi/2^48` (Parser added in #254).
- [x] Generate LS-Instructions. Because the very large size of a compiled QFT may be necessary to stream instructions rather than keeping them in memory. Currently we can generate LS-Instructions via LLOps (#247) which becomes unfeasible quickly, or from gates (#257) but it makes my compiler go out of memory (8GB+8GB) for about a 70 qubit QFT.
- [x] Generate LS-Slices / 3D-Assembly of lattice surgery instructions. The current slicer-router (patch_computation_composer) is far from even being able to compile a 10 qubit QFT. A new slicer-router that will read LS-Instructions [is being written in C++](https://github.com/latticesurgery-com/liblsqecc).
- [ ] View arbitrary windows of compiled slices.
- [ ] Compress sets of slices used to approximate angles into a single slice for viewing.

**Comment by gwwatkin** [comment]
Different pipelines we are looking at:
![image](https://user-images.githubusercontent.com/36427091/155364423-0e08404d-9656-4c1b-8489-5ee958b9ec25.png)
