### ISSUE TITLE
Webgui requirements

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#36]
To start, in order of priority:
- [x] Make the one page we have look half decent. Handled in #53
- [x] Add some example circuits
- [x] Make a page that displays quantum circuits in Pauli rotation form (Like Litinski). Show intermediate compilation stages like the Litinski transform and  the removal of Y operators.
- [ ] ~Make the website glamorous~ Split to #102 
- [ ] ~Add logins so users can upload and save their circuits~ Split to #103
- [ ] ~Integrate https://algassert.com/quirk so that users can drag and drop edit circuits~ Split to #104

**Comment by Keelando** [comment]
I will start on making a base template to make the website a bit more presentable.

**Comment by gwwatkin** [comment]
Split to #53

**Comment by Keelando** [comment]
Turned the remaining tasks into issues.
