### ISSUE TITLE
Unitary Fund Application

### ISSUE THREAD

**Issue by gwwatkin** [latticesurgery-com/lattice-surgery-compiler#98]
- [x] Meeting discussion:
    * Where do we want to take the project with the grant? 
         1. Short Term Goal: QASM to patch compilation. Make it appealing
         2. Long Term Goal: End to End QASM compiler
    * How long will it take to complete the project?
         1. TBD, but the problem is fairly open ended so we can set this arbitrarily. II propose the first quarter of 2022
    * How will we use the funding?
        1. development time, conference / travel fees, publication fees, web hosting
    * What else are we looking for to make our project successful?
       1. Need to make the project popular and gain a user base 
  * More notes in the comments and in this [this google docs](https://docs.google.com/document/d/1gbFhEFaLNTzgmmyzwJFuvw64-MZ_aBRZ1qlwXk1YI5k)
- [x] Draft application
    - 1000 characters in plain text form
- [x] Get feedback from Alexandru and Kero
- [x] Make a 2 minute introductory video:
    - >  This should be a < 2min video. Keep it simple and avoid spending time on video production. Just talking naturally into the camera works great
- [x] Fix up the repo's readme #108
- [x] Apply :metal:

Apply here https://unitary.fund/

**Comment by gwwatkin** [comment]
A starting point for reflection (notes with Kero)

**Part 1**
- What exists? Open Surgery other compilers
- what is missing? End to end error correcting compiler
- what can we add? Workflow, ease of access a desirable tool
- why people are interested? a practical tool to compile their circuits

**Part 2**
- How can we achieve the goal / vision
- Concrete steps to take (in the google doc) with timeline
- How will we use the grant money - development time / conference / travel fees / publication fees / web hosting

**Comment by gwwatkin** [comment]
## Application Draft
### What is your name? This question is required.
*If you're a team, then please include a list of all names.*
Team: George Watkins, Alex Nguyen, Varun Seshadri, Keelan Watkins. 
Advisors: Alexandru Paler, Hoi-Kwan Lau, Steven Pearce.
### What's your main contact email?
george_watkins@sfu.ca
### What is your project name? This question is required.
Lattice Surgery Quantum Error Correction Compiler
### Proposal Abstract
*(max 1000 characters)*
A proposed solution to mitigate the occurrence of errors in quantum computers are quantum error correcting codes (QECC). We focus on Lattice Surgery (LS) of surface codes. Recent work has focused on building compilers that translate an arbitrary quantum circuit to its equivalent error corrected version. Our goal is to publicly offer a way of adding error correction to quantum circuits using LS.  We will offer this functionality to any quantum programmer through a public web interface and as a Python package, both open sourced. So far, we have built part of the compiler and a web visualizer that converts a quantum circuit into abstract LS operations.  In this project to be funded, we will improve scalability of the compilation and of the visualization, to set up  the compiler as a micro service, and to implement methods for confirming the correctness of the resulting LS circuit.
https://docs.google.com/document/d/16Y3XX-ZHtsDqjBaDcniN2TLTpZRV3_8eVwQ-OcuFTr4
### Link to video proposal. It should clearly describe the proposed project, how it helps develop the quantum technology ecosystem, and why you have the skills/knowledge/background to build it. You can view an example video from a successful application at https://bit.ly/uf-example . This question is required. 
*This should be a < 2min video. Keep it simple and avoid spending time on video production. Just talking naturally into the camera works great.*
https://youtu.be/aIJrkZdUDGg
### How will you use the funding?
Development time, web hosting, conference and travel fees, publication fees.
### If funded, how many months will it take you to complete your project? We prefer projects that are less than six months, but can make exceptions. This question is required.
We aim at being done in 6 months. During the first 3 months, we plan addressing the problems of correctness and scaling. After that we plan on moving onto resource estimation and simulations with error models. We are leaving a gap at the end for additional refinements and maybe move onto error decoding. Near the end of the project, we plan to present our results at the Quantum Compiler session of the APS March Meeting (Mar 14-18, 2022). Detailed timeline in video.
### Are there some relevant links to your work that we should look at
Main Repository: https://github.com/latticesurgery-com/lattice-surgery-compiler. Public UI (Experimental) https://latticesurgery.com.
### Do you want your project to be granted special for access to Rigetti and IBM QPUs?
No.
### Is there anything else you'd like us to know? What else are you looking for to make your project successful?
Help sharing the project?
### Where did you hear about Unitary Fund?
C. Referred by a UF grant winner.
### If you heard about us through someone, some group, or in another way, can you tell us more about it?
Heard about it during a presentation.
###  Do you want us to use your contact email to keep you updated with news from Unitary Fund?
Yes.

**Comment by alexnguyenn** [comment]
**Suggestions:**
- "Work such as Alexandru Paler et al.'s OpenSurgery performs some of the compilation, to intermediate LS formats" - feels like this sentence doesn't fit here, might need to reword it.
- Add "hardware upgrade" (or something similar) to "how will you use the funding" question. 
- Also I think it is better to clearly specify who is advisor and who is team member in member list.

**Comment by gwwatkin** [comment]
* :heavy_check_mark:  Rephrased to  "A recent example of work in such direction is Alexandru Paler et al.'s OpenSurgery". There is no need to mention IR LS formats
* Might be hard to justify considering our project doesn't need to be computationally intensive. Also hardware is very expensive, a single new computer might take over the whole grant. I recommend using serverless hosting to run compilations on demand so we only pay for resources when we really need them. ~~I'll make an issue for it.~~ https://github.com/latticesurgery-com/compiler-lambda/issues/3
* :heavy_check_mark: Separated team and advisors

**Comment by Keelando** [comment]
I'm happy to continue contributing to this project part time as a web developer working on both the front end UI, the backend web server responsibilities as well as the deployment of the web application.

**Comment by gwwatkin** [comment]
### Meeting notes
Kero:
 * less time describing existing work
 * go into more details about what we are doing and will be doing

**Comment by alexnguyenn** [comment]
I think given Unitary fund's interest is, we should also highlights that we are making a website (so more people can access our tool) and publishing a Python package. Also we should be more in details about what we are planning in 6 months.

**Comment by gwwatkin** [comment]
Moved the paragraph and video information to this doc https://docs.google.com/document/d/16Y3XX-ZHtsDqjBaDcniN2TLTpZRV3_8eVwQ-OcuFTr4

**Comment by alexnguyenn** [comment]
@gwwatkin as anyone has the link can edit it, it is preferable that we not share it publicly.

**Comment by gwwatkin** [comment]
I set it to anyone can comment before sharing

**Comment by alexnguyenn** [comment]
mb, adding the link back: https://docs.google.com/document/d/16Y3XX-ZHtsDqjBaDcniN2TLTpZRV3_8eVwQ-OcuFTr4/edit?usp=sharing

**Comment by gwwatkin** [comment]
Application submitted!
